version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      .envs/.local/.flask
    command: flask run --host=0.0.0.0 --port=5000
