version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    ports:
      - "4000:80"
    volumes:
      - .:/usr/src/app
    env_file:
      .envs/.local/.flask
    command: flask run --host=0.0.0.0 --port=80
