version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    ports:
      - "4000:80"
    volumes:
      - .:/app
      - ./production.sqlite3:/app/production.sqlite3
    env_file:
      .envs/.production/.flask
    environment:
      - ENVIRONMENT_TYPE=production