version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    ports:
      - "4000:80"
    volumes:
      - .:/usr/src/app
      - production-db:/usr/src/app/production  # Path to the directory containing the SQLite database
    env_file:
      .envs/.production/.flask
    environment:
      - ENVIRONMENT_TYPE=production

volumes:
  production-db:  # This declares the volume used for the database
