version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    ports:
      - "4000:80"
    volumes:
      - .:/usr/src/app
    env_file:
      .envs/.production/.flask